import Footer from "@/components/common/Footer/Footer";
import Header from "@/components/common/Header/Header";
import ScrollToTop from "@/components/common/ScrollToTop";
import SmoothScrolling from "@/components/common/SmoothScrolling";
import { Mulish, Public_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistMulish = Mulish({
  variable: "--font-geist-mulish",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

const geistSans = Public_Sans({
  variable: "--font-geist-public-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata = {
  title: "RAMSPEED CY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`relative flex flex-col ${geistMulish.variable} ${geistSans.variable} antialiased`}
      >
        {" "}
        <SmoothScrolling>
          <Header />
          <Toaster />
          <ToastContainer />
          {children}
          <Footer />
          <ScrollToTop />
        </SmoothScrolling>
      </body>
    </html>
  );
}
